language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: OA2xx56CGrOb5mTmN8qeiQz0JHiuPpmjgzz6COwYxUS4slrdYDVDX9YsZw/i/HJ5Z1jurpnbjgIkV4ApdFJ0HOkhQ3km9Fc0RVnyjKSaZUBQp+7/oplaNEXaJtBW6SQJjdQhXJR+MMYgmItTPtAMYgz+DmLRWZtCCDaoyhmHzijqkmQ1Xujzu96DxFzbVNwFnvxlsfsukuTG/9kt2XC+mR9podLuSn/86le/gH+vYQk7zWyqHI2eelEiQ9GzJKFAuiS8ifAfOoVDBvw+Py5+vm1pyfHkeMRSHFLNLHepT86qS1aK5vhpfRZKKyz33MZDMLfoalHZ4XzCCmHxH1AewAGEsbsiW4RjNNghOspfysWpl/YgCtiXZQIO6XjhKSl9Td9JuNmvCeiXXxybExTRvjZ+NubLM16vaeebbp/MBL03IGZt5Ah1tEIUTZ95/dW0LUOukFOPGxP14eCfQGEvVAANeaZXGzpWOTLLoKGmI2bjdldpdyHWtyX3XtCPFreruM3inUzl+Abk0KULX7iHP9HmCpuQ39FPJ0HfoitUcQ9ExT6ju/HoOqzoX+oL4SmSLwTyHrBbWvogr9d8x+NjMGXSVUMynpaABLCz26tY/R4mJFJtIxVCJCqEgmgj5DZj3xDiLdj+kzOgvaxDZ40KU8jz88aGMJXNl2WVJUHCFWo=
  file:
    - 'rehype.js'
    - 'rehype.min.js'
  on:
    tags: true
